name: Release and Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  release-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Run Rollup
        run: npm run rollup

      - name: Run Google Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          changelog-types: '[{"type": "feat", "section": "Features", "hidden": false},{"type": "fix", "section": "Bug Fixes", "hidden": false},{"type": "perf", "section": "Performance", "hidden": false},{"type": "refactor", "section": "Refactoring", "hidden": false},{"type": "chore", "section": "Miscellaneous", "hidden": false},{"type": "build", "section": "Miscellaneous", "hidden": false},{"type": "deps", "section": "Dependencies", "hidden": false},{"type": "docs", "section": "Documentations", "hidden": false}]'
          release-type: node
          package-name: layla-ui-library
          bump-minor-pre-major: true

      - name: Publish to NPM
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'refs/heads/master' }}
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
